development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fedora-3.8.1
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fedora-3.8.1
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fedora-3.8.1